# Use a Node.js image as the base
FROM node:16

# Set the working directory inside the container
WORKDIR /app

# Copy the package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the frontend application
COPY . .

# Expose the port the frontend app will run on
EXPOSE 3001

# Start the frontend app
CMD ["npm", "start"]