# Use a Node.js image as the base
FROM node:16

# Set the working directory inside the container
WORKDIR /app

# Copy the package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application
COPY . .

# Expose the port the app will run on
EXPOSE 3000

# Set environment variables
ENV MONGO_URI="mongodb+srv://IncidentManagement:IncidentManagement123@incidentmanagement.2xu3n.mongodb.net/?retryWrites=true&w=majority&appName=IncidentManagement"
ENV JWT_SECRET="$mySuperSecretKey123!"
ENV PORT=3000

# Start the backend app
CMD ["npm", "start"]